const $ = (q) => document.querySelector(q);
const $$ = (q) => [...document.querySelectorAll(q)];
const esc = (s) => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon = (name) => `<svg aria-hidden="true"><use href="#i-${name}"/></svg>`;
const kinds = {document:['文档','file'],image:['图片','image'],video:['视频','video'],chat:['对话','chat'],text:['文本','file'],structured:['结构数据','code']};
const statusNames = {queued:'等待处理',parsing:'正在解析',writing:'正在写入',complete:'已完成',failed:'未完成'};
const state = {view:'memories',mode:'keyword',kind:'',user:'',source:'',query:'',page:1,total:0,items:[],sources:[],jobs:[],files:[],uploadTab:'files',uploading:false,overview:null,sequence:0};
let toastTimer;
function toast(text,error=false){const el=$('#toast');el.textContent=text;el.classList.toggle('error',error);el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,4500);}
function date(value){if(!value)return '时间未知';const d=new Date(value);return Number.isNaN(d.getTime())?'时间未知':d.toLocaleString('zh-CN',{year:'numeric',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false});}
function seconds(value){const n=Number(value||0);return `${String(Math.floor(n/60)).padStart(2,'0')}:${String(Math.floor(n%60)).padStart(2,'0')}`;}
function bytes(n){return n>=1024*1024?`${(n/1024/1024).toFixed(1)} MB`:`${Math.max(1,Math.round(n/1024))} KB`;}
function location(meta){if(meta.start_seconds!==undefined)return `${seconds(meta.start_seconds)}–${seconds(meta.end_seconds)}`;if(meta.page_start)return `第 ${meta.page_start} 页`;if(meta.extraction_method==='docx_text')return '正文 / 无页码';if(meta.tile_index!==undefined)return `图块 ${meta.tile_index+1}`;return '';}
function sourceName(item){return item.metadata.source_file?.split('/').pop() || (item.category==='chat'?'对话记忆':'文本记忆');}
function cleanText(s){return s.replace(/#{1,6}\s*/g,'').replace(/\*\*/g,'').replace(/\n+/g,' ').trim();}
function empty(title,description,upload=false){return `<div class="empty-state">${icon('stack')}<strong>${esc(title)}</strong><p>${esc(description)}</p>${upload?'<button class="button secondary" data-open-upload>添加第一份资料</button>':''}</div>`;}
async function api(path,options={}){const response=await fetch(path,{...options,headers:{'X-Memory-Client':'dashboard',...options.headers}});if(!response.ok){let message;try{const body=await response.json();message=typeof body.detail==='string'?body.detail:`请求失败（${response.status}）`;}catch{message=`请求失败（${response.status}）`;}throw new Error(message);}return response.json();}

async function overview(){const data=await api('/api/overview');const oldTotal=state.overview?.total;state.overview=data;$('#stat-total').textContent=data.total;$('#nav-count').textContent=data.total;$('#stat-sources').textContent=data.source_count;$('#stat-videos').textContent=data.categories.video||0;$('#stat-users').textContent=Object.keys(data.users).length;$('#connection-label').textContent='记忆库已连接';$('#model-label').textContent=`${data.embedding} · ${data.dimensions} 维`;$('#max-size').textContent=data.max_upload_mb;$('#file-picker').accept=data.extensions.join(',');$('#active-count').hidden=!data.jobs_active;$('#active-count').textContent=data.jobs_active;$('#connection-error').hidden=true;
  const users=Object.keys(data.users).sort();$('#user-filter').innerHTML='<option value="">所有用户</option>'+users.map(u=>`<option value="${esc(u)}">${esc(u||'未指定用户')}</option>`).join('');$('#user-filter').value=state.user;$('#user-options').innerHTML=users.filter(Boolean).map(u=>`<option value="${esc(u)}">`).join('');
  return oldTotal!==undefined&&oldTotal!==data.total;
}
function renderMemories(){const semantic=state.mode==='semantic'&&state.query;$('#result-label').textContent=semantic?`找到 ${state.total} 条相关记忆（最多 20 条）`:`共 ${state.total} 条记忆`;$('#sort-label').textContent=semantic?'按语义相关度排序':'最近写入优先';$('#clear-filter').hidden=!(state.query||state.kind||state.user||state.source);$('#source-filter-note').hidden=!state.source;$('#source-filter-note').textContent=state.source?`当前来源：${state.source}`:'';
  $('#memory-grid').innerHTML=state.items.length?state.items.map(item=>{const [name,mark]=kinds[item.category]||kinds.text;const loc=location(item.metadata);return `<button class="memory-card" data-memory="${esc(item.id)}" aria-label="查看记忆：${esc(sourceName(item))}"><div class="card-top"><span class="type-label ${esc(item.category)}">${icon(mark)}${name}</span>${loc?`<span class="location-pill">${esc(loc)}</span>`:item.score!==undefined?`<span class="score">相关度 ${(item.score*100).toFixed(1)}%</span>`:''}</div><h3 title="${esc(item.metadata.source_file||'对话记忆')}">${esc(sourceName(item))}</h3><p class="excerpt">${esc(cleanText(item.memory))}</p><div class="card-bottom"><span title="${esc(item.user_id)}">${esc(item.user_id||'未指定用户')}</span><span>${date(item.created_at)}</span>${icon('arrow')}</div></button>`;}).join(''):empty(state.query?'没有找到匹配的记忆':'这里暂时没有记忆',state.query?'试试更短的关键词，或切换到语义搜索。':'上传文件或写入文本，让资料成为可检索的记忆。',!state.query);
  const pages=Math.max(1,Math.ceil(state.total/12));$('#page-label').textContent=semantic?'显示相关度最高的结果':`第 ${state.page} / ${pages} 页 · 每页 12 条`;$('#prev').disabled=semantic||state.page<=1;$('#next').disabled=semantic||state.page>=pages;
}
async function loadMemories(){const ticket=++state.sequence;$('#memory-grid').innerHTML='<div class="loading-state">正在检索记忆…</div>';const semantic=state.mode==='semantic'&&state.query;const params=new URLSearchParams({q:state.query,user_id:state.user,kind:state.kind,source:state.source,page:String(state.page)});try{const data=await api(`${semantic?'/api/search':'/api/memories'}?${params}`);if(ticket!==state.sequence)return;state.items=data.items;state.total=data.total;renderMemories();}catch(error){if(ticket!==state.sequence)return;$('#memory-grid').innerHTML=empty('暂时无法读取记忆',error.message);toast(error.message,true);}}
function renderSources(){const q=$('#source-query').value.toLocaleLowerCase();const list=state.sources.filter(s=>s.source_file.toLocaleLowerCase().includes(q));$('#sources-list').innerHTML=list.length?`<div class="source-table"><div class="source-row header"><span>资料名称 / 状态</span><span class="scope-head">所属用户</span><span class="chunks-head">记忆片段</span><span>操作</span></div>${list.map((s,index)=>`<div class="source-row"><div class="source-name">${icon((kinds[s.category]||kinds.text)[1])}<div><strong>${esc(s.source_file)}</strong><small>${s.status==='failed'?`未入库 · ${esc(s.error||'文件解析失败')}`:`已入库 · ${esc(s.source_sha256?.slice(0,12)||'')}`}</small></div></div><span class="scope">${esc(s.user_id)}</span><span class="chunks">${s.chunks} 条</span>${s.status==='failed'?'<span class="state-badge failed">未完成</span>':`<button class="row-action" data-source="${index}">查看片段 →</button>`}</div>`).join('')}</div>`:empty('没有匹配的资料','试试其他文件名，或上传新的资料。');$('#sources-list').querySelectorAll('[data-source]').forEach(button=>button.addEventListener('click',()=>{const item=list[Number(button.dataset.source)];state.source=item.source_file;state.user=item.user_id;state.kind='';state.query='';state.page=1;$('#query').value='';$('#user-filter').value=state.user;syncFilters();showView('memories');}));}
async function loadSources(){const data=await api('/api/sources');state.sources=data.items;renderSources();}
function renderJobs(){const jobs=state.jobs;$('#jobs-list').innerHTML=jobs.length?jobs.map(j=>{const progress=j.chunks?Math.round(j.processed/j.chunks*100):0;const active=['queued','parsing','writing'].includes(j.status);return `<article class="job-card"><div class="job-icon">${icon('file')}</div><div class="job-body"><div class="job-title"><strong>${esc(j.filename)}</strong><span class="state-badge ${esc(j.status)}">${j.status==='complete'?'✓ ':''}${statusNames[j.status]||esc(j.status)}</span></div><p>${esc(j.error||j.message)}${j.status==='complete'?` · 新增 ${j.added} 条，跳过 ${j.skipped} 条`:j.status==='writing'?` · ${j.processed} / ${j.chunks} 条`:''}</p>${active?`<div class="job-progress ${j.status==='parsing'?'indeterminate':''}"><span style="width:${j.status==='parsing'?35:progress}%"></span></div>`:''}<div class="job-meta"><span>${bytes(j.size)} · ${esc(j.user_id)} · ${date(j.created_at)}</span>${j.status==='failed'?`<button class="text-button" data-retry="${esc(j.id)}">重试导入</button>`:j.status==='complete'?'<span>已同步到记忆总览</span>':'<span>可关闭此窗口，服务器会继续处理</span>'}</div></div></article>`;}).join(''):empty('还没有网页导入记录','已有资料可以在资料库中查看。新增上传任务会显示在这里。',true);}
async function loadJobs(){const data=await api('/api/jobs');state.jobs=data.items;if(state.view==='jobs')renderJobs();}
async function showView(view){state.view=view;const labels={memories:['记忆总览','查看、检索和追溯你的每一条记忆。'],sources:['资料库','从来源文件出发，查看每份资料留下的记忆。'],jobs:['导入记录','跟踪每份文件从上传到入库的处理状态。']};$('#page-title').textContent=labels[view][0];$('#breadcrumb').textContent=labels[view][0];$('#page-subtitle').textContent=labels[view][1];$$('[data-view]').forEach(el=>el.classList.toggle('active',el.dataset.view===view));$('#memory-view').hidden=view!=='memories';$('#sources-view').hidden=view!=='sources';$('#jobs-view').hidden=view!=='jobs';try{if(view==='memories')await loadMemories();if(view==='sources')await loadSources();if(view==='jobs')await loadJobs();}catch(error){toast(error.message,true);}}
function syncFilters(){$$('[data-kind]').forEach(b=>b.classList.toggle('selected',b.dataset.kind===state.kind));}
async function detail(id){const dialog=$('#detail-dialog');$('#detail-content').innerHTML='<div class="loading-state">正在读取详情…</div>';dialog.showModal();try{const item=await api(`/api/memories/${encodeURIComponent(id)}`);if(!dialog.open)return;const meta=item.metadata;const [label,mark]=kinds[item.category]||kinds.text;const fileUrl=`/api/memories/${encodeURIComponent(id)}/file`;let media='';if(item.category==='video'){media=`<video class="detail-media" controls preload="metadata" ${meta.preview_files?.length?`poster="${fileUrl}?asset=preview"`:""} src="${fileUrl}#t=${Number(meta.start_seconds||0)}"></video>`;}else if(item.category==='image'){media=`<img class="detail-media" src="${fileUrl}" alt="记忆来源图片" loading="lazy">`;}else if(meta.preview_file){media=`<img class="detail-media" src="${fileUrl}?asset=preview" alt="解析时的页面或图片" loading="lazy">`;}const loc=location(meta);$('#detail-content').innerHTML=`<span class="type-label ${esc(item.category)}">${icon(mark)}${label}</span><h2 id="detail-title">${esc(sourceName(item))}</h2><div class="detail-meta"><span>${esc(item.user_id||'未指定用户')}</span>${loc?`<span>${esc(loc)}</span>`:''}<span>${date(item.created_at)}</span></div>${media}${meta.source_path?`<div class="detail-actions"><a class="button secondary" href="${fileUrl}?download=true" target="_blank" rel="noopener">${icon('file')}下载原文件</a>${meta.source_type==='pdf'?`<a class="button secondary" href="${fileUrl}#page=${Number(meta.page_start||1)}" target="_blank" rel="noopener">预览 PDF ↗</a>`:''}</div>`:''}<p class="detail-label">记忆内容</p><pre class="memory-text">${esc(item.memory)}</pre>${meta.parsing_note?`<div class="notice">${esc(meta.parsing_note)}</div>`:''}${item.category==='video'?'<div class="notice">画面来自采样帧，可能遗漏瞬间动作；语音时间为片段范围，请回看原视频核对。</div>':''}<p class="detail-label">来源与定位</p><div class="detail-fields"><span>来源文件</span><strong>${esc(meta.source_file||'对话写入')}</strong><span>提取方式</span><strong>${esc(meta.extraction_method||'记忆提取')}</strong><span>记忆 ID</span><strong>${esc(item.id)}</strong>${meta.ingest_key?`<span>去重标识</span><strong>${esc(meta.ingest_key)}</strong>`:''}</div><details class="metadata"><summary>查看完整来源信息</summary><pre>${esc(JSON.stringify(meta,null,2))}</pre></details><p class="detail-label">写入历史</p>${Array.isArray(item.history)&&item.history.length?item.history.map(h=>`<div class="history-row">${esc({ADD:'创建记忆',UPDATE:'更新记忆',DELETE:'删除记忆'}[h.event]||h.event)}<small>${date(h.created_at||h.updated_at)}</small></div>`).join(''):'<p class="field-help">暂无历史记录</p>'}`;}catch(error){$('#detail-content').innerHTML=empty('详情读取失败',error.message);}}

function openUpload(){if(!state.uploading){$('#upload-error').hidden=true;$('#upload-progress').hidden=true;}$('#upload-dialog').showModal();}
function renderFiles(){$('#selected-files').innerHTML=state.files.map((f,i)=>`<div class="selected-file">${icon('file')}<span title="${esc(f.name)}">${esc(f.name)}</span><small>${bytes(f.size)}</small><button type="button" class="icon-button" data-remove="${i}" aria-label="移除 ${esc(f.name)}">${icon('close')}</button></div>`).join('');}
function addFiles(files){if(state.uploading)return;const allowed=state.overview?.extensions||[];const rejected=[];for(const f of files){const extension='.'+f.name.split('.').pop().toLowerCase();if(!allowed.includes(extension)||f.size>(state.overview?.max_upload_mb||512)*1024*1024){rejected.push(f.name);continue;}if(!state.files.some(x=>x.name===f.name&&x.size===f.size&&x.lastModified===f.lastModified))state.files.push(f);}if(state.files.length>20){state.files=state.files.slice(0,20);toast('一次最多选择 20 个文件',true);}if(rejected.length)toast(`未添加：${rejected.join('、')}。请检查格式和文件大小。`,true);renderFiles();}
function sendFile(file,user){return new Promise((resolve,reject)=>{const xhr=new XMLHttpRequest();xhr.open('POST',`/api/uploads?${new URLSearchParams({filename:file.name,user_id:user})}`);xhr.setRequestHeader('Content-Type','application/octet-stream');xhr.setRequestHeader('X-Memory-Client','dashboard');xhr.upload.onprogress=e=>{if(e.lengthComputable){const n=Math.round(e.loaded/e.total*100);$('#upload-bar').value=n;$('#upload-percent').textContent=n+'%';}};xhr.onload=()=>{let body;try{body=JSON.parse(xhr.responseText);}catch{reject(new Error('服务器返回异常，请刷新检查导入记录'));return;}if(xhr.status<200||xhr.status>=300){reject(new Error(typeof body.detail==='string'?body.detail:'上传失败'));return;}resolve(body);};xhr.onerror=()=>reject(new Error('上传连接中断，请检查网络后重试'));xhr.send(file);});}
async function submitUpload(){if(state.uploading)return;const user=$('#upload-user').value.trim();let files=[...state.files];if(state.uploadTab==='text'){const content=$('#text-content').value.trim();if(!content){toast('请先填写记忆内容',true);return;}const title=($('#text-title').value.trim()||'文本记忆').replace(/[\\/]/g,'-');files=[new File([content],`${title}.txt`,{type:'text/plain'})];}if(!files.length){toast('请先选择文件',true);return;}if(!user){toast('请填写所属用户',true);return;}state.uploading=true;$('#submit-upload').disabled=true;$('#upload-user').disabled=true;$('#upload-progress').hidden=false;$('#upload-error').hidden=true;let done=0;try{for(const file of files){$('#upload-progress-label').textContent=`正在上传 ${done+1}/${files.length}：${file.name}`;$('#upload-bar').value=0;$('#upload-percent').textContent='0%';await sendFile(file,user);done++;}state.files=[];renderFiles();$('#file-picker').value='';$('#text-title').value='';$('#text-content').value='';$('#upload-dialog').close();toast(`已接收 ${done} 份资料，正在后台导入`);await showView('jobs');await overview();}catch(error){$('#upload-error').textContent=`${done?`前 ${done} 份已接收。`:''}${error.message}`;$('#upload-error').hidden=false;}finally{state.uploading=false;$('#submit-upload').disabled=false;$('#upload-user').disabled=false;}}

$$('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
$('#open-upload').addEventListener('click',openUpload);
$$('[data-close]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.close==='upload-dialog'&&state.uploading){toast('正在上传，请等待传输完成');return;}$('#'+b.dataset.close).close();}));
$('#upload-dialog').addEventListener('cancel',event=>{if(state.uploading)event.preventDefault();});
$$('dialog').forEach(dialog=>dialog.addEventListener('click',event=>{if(event.target===dialog){const rect=dialog.getBoundingClientRect();if(event.clientX<rect.left||event.clientX>rect.right||event.clientY<rect.top||event.clientY>rect.bottom){if(!state.uploading||dialog.id!=='upload-dialog')dialog.close();}}}));
$('#search-form').addEventListener('submit',event=>{event.preventDefault();state.query=$('#query').value.trim();state.page=1;loadMemories();});
$$('[data-mode]').forEach(b=>b.addEventListener('click',()=>{state.mode=b.dataset.mode;$$('[data-mode]').forEach(el=>el.classList.toggle('selected',el===b));$('#query').placeholder=state.mode==='semantic'?'用自然语言提问，例如：机器人可以完成哪些家务？':'搜索记忆内容或文件名…';$('#search-hint').textContent=state.mode==='semantic'?'语义搜索使用已配置的向量模型，返回最相关的 20 条记忆。':'关键词匹配内容和文件名；切换到语义搜索，可用自然语言提问。';state.query=$('#query').value.trim();state.page=1;loadMemories();}));
$$('[data-kind]').forEach(b=>b.addEventListener('click',()=>{state.kind=b.dataset.kind;state.page=1;syncFilters();loadMemories();}));
$('#user-filter').addEventListener('change',event=>{state.user=event.target.value;state.page=1;loadMemories();});
$('#clear-filter').addEventListener('click',()=>{Object.assign(state,{kind:'',user:'',source:'',query:'',page:1});$('#query').value='';$('#user-filter').value='';syncFilters();loadMemories();});
$('#prev').addEventListener('click',()=>{state.page--;loadMemories();window.scrollTo({top:200,behavior:'smooth'});});$('#next').addEventListener('click',()=>{state.page++;loadMemories();window.scrollTo({top:200,behavior:'smooth'});});
$('#source-query').addEventListener('input',renderSources);
document.addEventListener('click',async event=>{const memory=event.target.closest('[data-memory]');if(memory)detail(memory.dataset.memory);if(event.target.closest('[data-open-upload]'))openUpload();const remove=event.target.closest('[data-remove]');if(remove&&!state.uploading){state.files.splice(Number(remove.dataset.remove),1);renderFiles();}const retry=event.target.closest('[data-retry]');if(retry){retry.disabled=true;try{await api(`/api/jobs/${encodeURIComponent(retry.dataset.retry)}/retry`,{method:'POST'});await loadJobs();}catch(error){toast(error.message,true);retry.disabled=false;}}});
$('#dropzone').addEventListener('click',()=>{if(!state.uploading)$('#file-picker').click();});$('#file-picker').addEventListener('change',event=>addFiles(event.target.files));
['dragenter','dragover'].forEach(name=>$('#dropzone').addEventListener(name,event=>{event.preventDefault();$('#dropzone').classList.add('drag');}));['dragleave','drop'].forEach(name=>$('#dropzone').addEventListener(name,event=>{event.preventDefault();$('#dropzone').classList.remove('drag');if(name==='drop')addFiles(event.dataTransfer.files);}));
$$('[data-upload-tab]').forEach(b=>b.addEventListener('click',()=>{if(state.uploading)return;state.uploadTab=b.dataset.uploadTab;$$('[data-upload-tab]').forEach(x=>x.classList.toggle('selected',x===b));$('#file-upload-pane').hidden=state.uploadTab!=='files';$('#text-upload-pane').hidden=state.uploadTab!=='text';}));
$('#submit-upload').addEventListener('click',submitUpload);
async function refresh(){const button=$('#refresh');button.classList.add('spinning');try{await overview();await showView(state.view);}catch(error){$('#connection-error').textContent='无法连接服务：'+error.message;$('#connection-error').hidden=false;$('#connection-label').textContent='连接异常';}finally{button.classList.remove('spinning');}}
$('#refresh').addEventListener('click',refresh);
await refresh();
let polling=false;setInterval(async()=>{if(document.hidden||polling)return;polling=true;try{const changed=await overview();await loadJobs();if(changed&&state.view==='memories')await loadMemories();if(state.view==='sources')await loadSources();}catch{ $('#connection-label').textContent='连接暂时中断';}finally{polling=false;}},5000);
